export const content = {
    en: {
        gallery: "Gallery",
        admin: "Admin",
        title_start: "Vehicle Paint",
        title_end: "Schemes",
        subtitle: "Explore the latest nano-coating and paint protection finishes.",
        toggle_lang: "中 / En",
        admin_dashboard: "Dashboard",
        upload_new: "Upload New Photo",
        photo_title: "Photo Title",
        category: "Category (e.g. Matte, Gloss)",
        drag_drop: "Drag & drop or click to select image",
        click_change: "Click to change",
        upload_btn: "Upload to Feed",
        manage_photos: "Manage Photos",
        admin_login: "Admin Login",
        enter_password: "Enter Password",
        unlock_panel: "Unlock Panel",
        no_photos: "No photos yet. Visit admin panel to upload.",
        download: "Download",
        logout: "Logout",
    },
    zh: {
        gallery: "画廊",
        admin: "后台管理",
        title_start: "车辆涂装",
        title_end: "方案",
        subtitle: "探索最新的纳米涂层和漆面保护工艺。",
        toggle_lang: "En / 中",
        admin_dashboard: "仪表盘",
        upload_new: "上传新图片",
        photo_title: "图片标题",
        category: "分类 (例如: 哑光, 亮光)",
        drag_drop: "拖放或点击选择图片",
        click_change: "点击更换",
        upload_btn: "发布到展示墙",
        manage_photos: "图片管理",
        admin_login: "管理员登录",
        enter_password: "请输入密码",
        unlock_panel: "进入后台",
        no_photos: "暂无图片，请前往后台上传。",
        download: "下载原图",
        logout: "退出登录",
    }
};

export type ContentKey = keyof typeof content.en;
